import json
import os
from typing import Any

import boto3

from services.shared.shared_utils import create_correlation_id, log, utc_now

bedrock = boto3.client("bedrock-runtime")
dynamodb = boto3.resource("dynamodb")
plans_table = dynamodb.Table(os.getenv("REMEDIATION_TABLE", "remediation_plans"))
model_id = os.getenv("BEDROCK_MODEL_ID", "anthropic.claude-3-5-sonnet-20241022-v2:0")


def handler(event: dict[str, Any], _context: Any) -> dict[str, Any]:
    correlation_id = create_correlation_id()
    finding_id = event["findingId"]
    os_variant = event.get("osVariant", "linux")
    summary = event.get("summary", "")

    prompt = (
        f"Generate a safe remediation and rollback for finding {finding_id}. "
        f"Summary: {summary}. OS={os_variant}."
    )
    response = bedrock.invoke_model(
        modelId=model_id,
        body=json.dumps({"prompt": prompt, "max_tokens": 500}),
        contentType="application/json",
        accept="application/json",
    )
    plan_text = response["body"].read().decode("utf-8")

    plan = {
        "findingId": finding_id,
        "planId": f"{finding_id}-{int(__import__('time').time())}",
        "script": f"echo '{plan_text[:200]}'",
        "rollbackScript": "echo 'rollback guidance required before auto-approval'",
        "impactAnalysis": "Generated by model with deterministic guardrails applied post-generation",
        "riskScore": 62,
        "confidenceScore": 0.71,
        "osVariant": os_variant,
        "approvalState": "pending",
        "createdAt": utc_now(),
    }
    plans_table.put_item(Item=plan)
    log("INFO", "Generated remediation plan", {"correlationId": correlation_id, "planId": plan["planId"]})
    return plan
